version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
  pre_build: 
    commands:
      - echo "run tests here"
  build:
    commands: 
      - echo "build FE static assets"
  post_build:
    commands:
      - export AWS_ACCESS_KEY_ID=AKIAQ5VWXCYXNTAPZUPF
      - export AWS_SECRET_ACCESS_KEY=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
      - serverless deploy -v
  
